#!/usr/bin/env node
/**
 * Assemble a DWC 3.6-shaped plugin source tree in a staging directory.
 *
 * DWC's plugin builder (both generations) copies a fixed `<pluginDir>/src` and compiles
 * `src/index.js`. It cannot be pointed at `src/ui36/`, and it would happily copy — and,
 * for anything the entry reaches, compile — `src/ui37/` too, which fails immediately
 * because Vuetify 4, Pinia and `@/plugins` do not exist in a 3.6 checkout. So rather
 * than fight it, stage a tree that holds only what the 3.6 build needs.
 *
 * The staged tree keeps the repo's directory shape exactly (`ui36/` stays a
 * subdirectory), so every relative import inside `core/` and `ui36/` resolves
 * unchanged. The only new file is a one-line `src/index.js` naming the 3.6 entry,
 * mirroring what the repo's own `src/index.js` does for the default build.
 *
 *   node scripts/stage-dwc36.mjs [outDir]
 *
 * Prints the staged directory as its last line, for the caller to pass to
 * `npm run build-plugin-pkg -- <dir>` in a DuetWebControl 3.6 checkout.
 */
import { cpSync, existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { dirname, join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const repo = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const outDir = resolve(process.argv[2] ?? join(tmpdir(), 'dwc-vigil-dwc36'))

/** Shared, version-neutral sources plus the 3.6 UI. `ui37/` is deliberately absent. */
const INCLUDE = ['core', 'ui36']

/**
 * Bundled dependencies that must NOT come from the DWC checkout.
 *
 * Webpack resolves package imports by walking up from the importing file, so a copy in
 * `<stage>/src/node_modules/` — which lands as `src/plugins/Vigil/node_modules/` inside
 * the DWC checkout — is found before the checkout's own. That is how the plugin can use
 * a different major of a package DWC 3.6 also ships, without breaking DWC's own uses of
 * it.
 *
 * chart.js is exactly that case: DWC 3.6 ships 2.9 and its own temperature and layer
 * charts are written against it, while src/core/charts.js is Chart.js 4 (which is what
 * the 3.7 build bundles, since DWC 3.7 does not expose chart.js to plugins at all).
 * Vendoring keeps both working off one set of chart configs, with no manual preparation
 * of the 3.6 checkout.
 */
const VENDOR = ['chart.js']

/** Plugin files the builder reads from the plugin directory rather than from src/. */
const PLUGIN_FILES = ['plugin.json']
const PLUGIN_DIRS = ['dsf']

rmSync(outDir, { recursive: true, force: true })
mkdirSync(join(outDir, 'src'), { recursive: true })

for (const entry of INCLUDE) {
    cpSync(join(repo, 'src', entry), join(outDir, 'src', entry), { recursive: true })
}

// The builder reads dsf/ (and dwc/, sd/) from the plugin directory, not from src/, and
// populates dsfFiles from what it finds — so the daemon has to travel with the stage.
// __pycache__ is filtered rather than assumed absent: a local pytest run leaves it in
// the repo, and it must never reach the ZIP.
for (const dir of PLUGIN_DIRS) {
    const from = join(repo, dir)
    if (existsSync(from)) {
        cpSync(from, join(outDir, dir), {
            recursive: true,
            filter: (src) => !src.split(/[\\/]/).includes('__pycache__'),
        })
    }
}

/**
 * Copy a package and, recursively, everything it depends on. npm's flat layout makes
 * this a simple walk of the repo's own node_modules. Without the closure webpack stops
 * at the first transitive import it cannot resolve (chart.js needs @kurkle/color).
 */
function vendor(name, seen) {
    if (seen.has(name)) {
        return
    }
    seen.add(name)
    const from = join(repo, 'node_modules', name)
    if (!existsSync(from)) {
        throw new Error(`Cannot vendor ${name}: not installed. Run npm ci at the repo root first.`)
    }
    cpSync(from, join(outDir, 'src', 'node_modules', name), { recursive: true })
    let deps = {}
    try {
        deps = JSON.parse(readFileSync(join(from, 'package.json'), 'utf8')).dependencies ?? {}
    } catch {
        // no manifest / unreadable — nothing further to pull in
    }
    for (const dep of Object.keys(deps)) {
        vendor(dep, seen)
    }
}

const vendored = new Set()
for (const dep of VENDOR) {
    vendor(dep, vendored)
}

writeFileSync(
    join(outDir, 'src', 'index.js'),
    `/**
 * Generated by scripts/stage-dwc36.mjs — do not edit.
 *
 * DWC's plugin builder always compiles src/index.js; for the DWC 3.6 package that has
 * to be the Vue 2.7 / Vuetify 2 entry point rather than the repo's default one.
 */
import './ui36/index'
`,
)

// The manifest travels with the source. `dwcVersion: "auto-major"` is resolved by the
// builder against whichever DWC is doing the building, so the same file yields a
// 3.6-tagged package here and a 3.7-tagged one from the 3.7 builder — no second
// manifest to keep in sync.
for (const file of PLUGIN_FILES) {
    cpSync(join(repo, file), join(outDir, file))
}

const manifest = JSON.parse(readFileSync(join(repo, 'plugin.json'), 'utf8'))
console.log(
    `Staged DWC 3.6 sources for ${manifest.id} v${manifest.version}`
    + (vendored.size > 0 ? `, vendoring: ${[...vendored].join(', ')}` : ''),
)
console.log(outDir)
